### ISSUE TITLE
Bot gets stuck on liking one media 

### ISSUE THREAD

**Issue by ghost** [EVOKE-YUJI/instabot.rb#8]
Hi!
So every time I run the bot it likes for a couple posts and then gets caught in an infinite loop trying to like a post it can't like for some reason. Here's what I found in my log file:

[127] [05:05:15 18-01-28] [ACTIONS] -- : trying to like a media[1702250012426633087]
[128] [05:05:15 18-01-28] [LOGIN] -- : checking loging status
[129] [05:05:46 18-01-28] [GRABBER] -- : Trying to get media (Befm10-guvv) information
[130] [05:05:46 18-01-28] [GRABBER] -- : Trying to get media (Befm10-guvv) information
[131] [05:05:46 18-01-28] [GRABBER] -- : Trying to get media (Befm10-guvv) information
[132] [05:05:46 18-01-28] [GRABBER] -- : Trying to get media (Befm10-guvv) information
....

This line is repeated thousands of times in the log file. Please help! 

Thanks,
D

**Comment by eVanilla** [comment]
mhmm.. i checked the bot.. there is no problem with it, can you show me your configurations that you're using(except the sensitive information)?

**Comment by ghost** [comment]
@eVanilla 
Here's my configs! Essentially I wanted to to setup the bot to only like media and not follow/unfollow or comment. Thanks for the help and the quick reply, I really appreciate it!

Config.setup do |set|
  set.username              = '---'
  set.password              = '---'
  set.tags                  =['photography', 'art', 'heatercentral', 'agameoftones', 'fatalframes', 'artofvisuals', 
'moodygrams', 'pdx', 'portland', 'pnw', 'portraitpage', 'moodyports', 'wethecreators', 
'thecreatorclass', 'exploretocreate', 'tangledinfilm', 'theimaged', 'creative', 'discoverportrait',
'artistoninstagram', 'vscocam', 'vsco', 'humanedge', 'photooftheday', 'photography', 'popart',
'painting', 'polaroid', 'paint', 'expofilm', 'gramslayers', 'livefolk', 'teamcozy', 
'visual', 'visualcreators', 'justgoshoot', 'details', 'createcommune', 'artofvisuals', 'artist',
'artistsoninstagram', 'digitalart', 'ig_color', 'artcollective', 'drawing', 'ig_today',
'shotoftheday', 'great_captures', 'main_vision', 'photographer', 'theportraitpr0ject',
'liveauthentic', 'gramkilla', 'featurepalette', 'featuremeseas', 'portraitcentral', 'theoutbound',
'mchfeature', 'visualambassadors', 'way2ill', 'alphacollective', 'socality', 'instaminimal',
'lineart', 'artsy', 'graphicdesign', 'designer', 'aesthetic', 'aesthetics']

  set.wait_per_action       = 30
  set.max_follow_per_day    = 0
  set.max_unfollow_per_day  = 0
  set.max_like_per_day      = 2000
  set.max_comment_per_day   = 0

  set.print_banner          = true
  set.log_status            = true
  set.infinite_tags         = false
  set.add_tag_per_post      = 0
  set.pre_load              = false

  set.unwanted_list        = []
  set.white_list_users     = []



  set.comments             = []
end

bot = Instabot.new
bot.mode(:infinite) # => :cleanup, :infinite, ...

**Comment by ghost** [comment]
@eVanilla Also, here's the repeating error I'm getting in the console. It looks like it wants to ignore the media it's having trouble liking, but ends up repeatedly trying to like the same media. Thanks!

[+] [LIKE] 2934 MEDIA IS READY
[+] Trying to get media (BegudF4nxKV) information
An error occured ... Mechanize::ResponseCodeError 404 => Net::HTTPNotFound for https://www.instagram.com/p/BegudF4nxKV/?__a=1 -- unhandled response
["/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/grabber.rb:29:in `handle_media_information_data'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/modes.rb:125:in `auto_like'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/modes.rb:26:in `block in mode'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/modes.rb:12:in `loop'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/modes.rb:12:in `mode'", "automatic_example.rb:50:in `<main>'"]
[ignored]
[+] [LIKE] 2934 MEDIA IS READY
[+] Trying to get media (BegudF4nxKV) information
An error occured ... Mechanize::ResponseCodeError 404 => Net::HTTPNotFound for https://www.instagram.com/p/BegudF4nxKV/?__a=1 -- unhandled response
["/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/grabber.rb:29:in `handle_media_information_data'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/modes.rb:125:in `auto_like'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/modes.rb:26:in `block in mode'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/modes.rb:12:in `loop'", "/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/instabot-0.1.81/lib/instabot/modes.rb:12:in `mode'", "automatic_example.rb:50:in `<main>'"]
[ignored]

**Comment by eVanilla** [comment]
Your configurations is fine, weird... it works perfectly fine for me it's have been running for an hour and still getting no error
also this error tells you that the page does not exist.. still weird, i'm so busy in this while but I'll take a look at it and see what's the problem

**Comment by eVanilla** [comment]
@heydanaye well i fixed the problem, and you just need to update the gem and it should works fine.
And if your problem is solved, please close this issue

**Comment by ghost** [comment]
@eVanilla Everything seems to be perfectly working now! Thank you!
